### ISSUE TITLE
Check before updating nextIndex and matchIndex

### ISSUE THREAD

**Issue by markcty** [eliben/raft#16]
In Part3 code, function `leaderSendAEs`.
For example: After a leader sends an empty ae(heartbeat) to followers, it immediately receives a command and sends an ae with a new log to followers. If the response of the 2nd ae arrives earlier than the 1st ae due to some network glitch, the `nextIndex` and `matchIndex` will be set to the newer(larger) one and set back to the smaller one. It's better to check in line 633 that `ni + len(entries)` is larger than `nextIndex` before updating it.

**Comment by eliben** [comment]
I'm not sure if you're suggesting a bug fix or performance improvement here; could you clarify?

**Comment by markcty** [comment]
Sry, I mean a performance improvement. If the situation I described happened, the wrong `nextIndex` and `matchIndex` should be fixed in the next heartbeat. The cost here is to wait for another round of heartbeat and unnecessary logs will be sent over the network (since we need to start sending from the smaller `nextIndex` again).

**Comment by eliben** [comment]
OK, so just to be clear - my implementation doesn't attempt to be the fastest. It optimizes for clarity. There are a number of scenarios where the implementation could be somewhat more efficient in special cases, but this complicates the code. In this case since you're talking about a fairly unlikely occurrence I'm inclined to leave the code as is; if there was a correctness issue it would need a fix, but I'm not particularly sensitive to being a bit less efficient than needed in such rare cases.
